### ISSUE TITLE
How to get to Santa Barbara?

### ISSUE THREAD

**Issue by peacekeeper** [WebOfTrustInfo/rebooting-the-web-of-trust-spring2018#1]
wtf?

![screenshot from 2018-01-25 11-59-19](https://user-images.githubusercontent.com/290941/35385151-b5f77da4-01c7-11e8-983e-93d22e753cd1.png)

**Comment by ChristopherA** [comment]
There are landslides over hwy 1 being repaired.

There is a Santa Barbara airport.

— Christopher Allen [via iPhone]

**Comment by peacekeeper** [comment]
Thanks, for us "international" people I suspect it may be easier to fly to LAX and then drive, rather than trying to find a connection to this one.

**Comment by joaosantos15** [comment]
Hey :)
I saw that there are trains: https://www.wanderu.com/en/train-tickets/us-ca/los-angeles/us-ca/santa-barbara/ 
Might end up being the best option

**Comment by katelynsills** [comment]
To anyone looking at this now, google maps says the way is clear!
