### ISSUE TITLE
Paper submission

### ISSUE THREAD

**Issue by csuwildcat** [WebOfTrustInfo/rebooting-the-web-of-trust-spring2018#19]
I would like to submit this technical explainer for consideration at the event: https://github.com/decentralized-identity/did-methods/blob/master/sidetrees/explainer.md

Do I do so via GH Issue, or a pull to the repo MD file?

**Comment by ChristopherA** [comment]
A PR is best.

**Comment by shannona** [comment]
Verified that this has been submitted.
