### ISSUE TITLE
DID Auth: Adjust away from "identity" and "ownership"

### ISSUE THREAD

**Issue by jandrieu** [WebOfTrustInfo/rebooting-the-web-of-trust-spring2018#96]
In the DID-Auth paper, https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/blob/master/draft-documents/did_auth_draft.md, the term "identity owner" is used as a cornerstone for discussing who controls a DID.

Unfortunately, "ownership" is a legal point of fact and will be adjudicated by the courts. Even if a thief steals your private keys and proves control of a DID, if you can prove the theft, courts will NOT recognize the thief as owner. So control != ownership so referring to the controller as the owner is an unfortunate shortcut.

Second, although DIDs and DID documents enable proof of control over the DID document, they do not establish control over the entire resulting identity. In particular, any verifiable credential "about" that DID may or may not be owned or even controlled by the controller of the DID.

For example, wrt a digital driver's license, issued to a DID. Who owns the driver's license? Who controls it? Almost certainly, the Department of Motor Vehicles controls it. Not the DID controller. Even if the credential is literally sold to another individual, along with the DID key, it would not transfer the privilege of driving. 

Which is to say that part of the identity--or one of the identities--as manifest in that driver's license is NOT fully under the control or ownership of the subject.

So, yes, the licensed driver could prove the DID in the credential is under their control, but that does NOT mean they have control over the credential itself. The full identity is the combination of DIDs + VCs + how both are created, stored, used, and governed that comprises the actual identity. At best, DIDs demonstrate control over one or more anchors to an identity, which itself can manifest across myriad of verifiers.

Perhaps more important, the DMV has a bunch of non-DID-based authentication policies and procedures. The credentials and information they use to identify individuals is completely outside the scope of DIDs. The DMV *will* have an internal record, an internal identity, for everyone it issues a driver's license or ID card to. That identity doesn't suddenly become owned or controlled by the licensee just because the DMV uses a DID as the public facing identifier on a digital credential.

Although these may seem like minor tweaks, I think it's important to frame DIDs and DID-Auth rigorously in terms of what they can actually do rather than fall into industry vernacular that can and will be read differently by outsiders trying to understand our work. In particular, the twittersphere is still reeling from the early advocacy that DIDs give people control over their identity--notable leaders in this space advocated DIDs as a panacea for just about every privacy problem on the Internet and off. They aren't. They are a vital cornerstone in a new framework that promises to restructure how identity works. They aren't magic fairy dust that gives us control over all the information organizations use to recognize, remember, and respond to us as specific people. The use of "identity owner" reads like magic fairy dust to me.

@peacekeeper @kdenhartog @christianlundkvist @AlbertoElias @andrewhughes3000 @jljordan42 @dmitrizagidulin 

I think these suggestions could be adopted without changing the fundamental work. If you're open to the changes, I would be happy to make a stab at a PR.

**Comment by AlbertoElias** [comment]
I have to admit I hadn't thought about the points you raised Joe, and I definitely agree with them. That said, I think we should conform to what the DID spec says, and if this term isn't appropriate, we should discuss it there

**Comment by peacekeeper** [comment]
Proposing to add a section here: https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-spring2018/pull/98

**Comment by peacekeeper** [comment]
Fixed by #98
